/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import Common.Utilidades;
import Common.cConfiguracion;
import Common.cDatosException;
import Common.cJuego;
import Common.cJugador;
import Common.cUsuario;
import Dominio.dEmpresa;
import Patrones.Observer.ClaseObservador;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import static java.lang.Thread.sleep;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maxi
 */
public class vBingoGame extends javax.swing.JFrame implements Observer{
    private dEmpresa empresa;
    private ClaseObservador observer;
    private vPlayer1 Iplayer1;
    private static cJuego elJuego;
    private Integer[] Numeros;
    public static int clicks;
    public static int si;
    public static int no;
    
    /**
     * Creates new form BingoGame
     */
    public vBingoGame() {
        initComponents();
    }
    public vBingoGame(dEmpresa pEmp, ClaseObservador pObservador) {
        empresa = pEmp;
        observer = pObservador;
        Iplayer1 = new vPlayer1(empresa, observer);
        
        observer.addObserver(Iplayer1);
        initComponents();
    }
    public vBingoGame(ClaseObservador pObservador) {
        observer = pObservador;
        initComponents();
    }
    public vBingoGame(dEmpresa pEmp) {
        empresa = pEmp;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboColores = new javax.swing.JComboBox();
        panelSeleccion = new javax.swing.JPanel();
        label1010 = new javax.swing.JLabel();
        label123 = new javax.swing.JLabel();
        comboSelect = new javax.swing.JComboBox();
        label12313 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelLogin1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUserName1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        txtPassword1 = new javax.swing.JPasswordField();
        panelLogin2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtUserName2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnLogin2 = new javax.swing.JButton();
        txtPassword2 = new javax.swing.JPasswordField();
        panelLogin3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUserName3 = new javax.swing.JTextField();
        btnLogin3 = new javax.swing.JButton();
        txtPassword3 = new javax.swing.JPasswordField();
        lblEstado1 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        lblEstado3 = new javax.swing.JLabel();
        btnLogout1 = new javax.swing.JButton();
        btnLogout2 = new javax.swing.JButton();
        btnLogout3 = new javax.swing.JButton();
        lblPlayer1 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        lblPlayer3 = new javax.swing.JLabel();
        lblMensajeCombo = new javax.swing.JLabel();
        PanelJuego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPozo = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        lblBolilla = new javax.swing.JLabel();
        btnSortear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        comboColores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rojo", "Negro", "Amarillo" }));
        comboColores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboColoresItemStateChanged(evt);
            }
        });
        jPanel1.add(comboColores);
        comboColores.setBounds(110, 10, 56, 20);

        panelSeleccion.setOpaque(false);
        panelSeleccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1010.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label1010.setForeground(new java.awt.Color(255, 255, 255));
        label1010.setText("Player 1: ");
        panelSeleccion.add(label1010, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        label123.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label123.setForeground(new java.awt.Color(255, 255, 255));
        label123.setText("Player 2:");
        panelSeleccion.add(label123, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        comboSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3" }));
        comboSelect.setToolTipText("");
        comboSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboSelectMouseClicked(evt);
            }
        });
        comboSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSelectItemStateChanged(evt);
            }
        });
        comboSelect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboSelectFocusGained(evt);
            }
        });
        panelSeleccion.add(comboSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 47, -1));

        label12313.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label12313.setForeground(new java.awt.Color(255, 255, 255));
        label12313.setText("Player 3: ");
        panelSeleccion.add(label12313, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de Jugadores");
        panelSeleccion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        panelLogin1.setPreferredSize(new java.awt.Dimension(187, 106));

        jLabel4.setText("Usuario");

        txtUserName1.setText("firuges");

        jLabel6.setText("Password");

        btnLogin1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin1.setText("Login");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        txtPassword1.setText("elfacha");

        javax.swing.GroupLayout panelLogin1Layout = new javax.swing.GroupLayout(panelLogin1);
        panelLogin1.setLayout(panelLogin1Layout);
        panelLogin1Layout.setHorizontalGroup(
            panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogin1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(txtUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLogin1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtPassword1)))
                .addContainerGap())
            .addGroup(panelLogin1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLogin1Layout.setVerticalGroup(
            panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelSeleccion.add(panelLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 110));

        jLabel8.setText("Usuario");

        txtUserName2.setText("firu");

        jLabel7.setText("Password");

        btnLogin2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin2.setText("Login");
        btnLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin2ActionPerformed(evt);
            }
        });

        txtPassword2.setText("elfacha");

        javax.swing.GroupLayout panelLogin2Layout = new javax.swing.GroupLayout(panelLogin2);
        panelLogin2.setLayout(panelLogin2Layout);
        panelLogin2Layout.setHorizontalGroup(
            panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPassword2)
                    .addComponent(txtUserName2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(13, 13, 13))
            .addGroup(panelLogin2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelLogin2Layout.setVerticalGroup(
            panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUserName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin2)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelSeleccion.add(panelLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        panelLogin3.setPreferredSize(new java.awt.Dimension(187, 106));

        jLabel9.setText("Password");

        jLabel10.setText("Usuario");

        txtUserName3.setText("redik");

        btnLogin3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin3.setText("Login");
        btnLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLogin3Layout = new javax.swing.GroupLayout(panelLogin3);
        panelLogin3.setLayout(panelLogin3Layout);
        panelLogin3Layout.setHorizontalGroup(
            panelLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogin3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(txtUserName3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLogin3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtPassword3)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogin3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panelLogin3Layout.setVerticalGroup(
            panelLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtUserName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelSeleccion.add(panelLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        lblEstado1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstado1.setForeground(new java.awt.Color(0, 204, 51));
        lblEstado1.setText("OFFLINE");
        panelSeleccion.add(lblEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        lblEstado2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstado2.setForeground(new java.awt.Color(0, 204, 51));
        lblEstado2.setText("OFFLINE");
        panelSeleccion.add(lblEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        lblEstado3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstado3.setForeground(new java.awt.Color(0, 204, 51));
        lblEstado3.setText("OFFLINE");
        panelSeleccion.add(lblEstado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        btnLogout1.setText("Salir");
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        panelSeleccion.add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        btnLogout2.setText("Salir");
        btnLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout2ActionPerformed(evt);
            }
        });
        panelSeleccion.add(btnLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        btnLogout3.setText("Salir");
        btnLogout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout3ActionPerformed(evt);
            }
        });
        panelSeleccion.add(btnLogout3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));

        lblPlayer1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPlayer1.setForeground(new java.awt.Color(255, 255, 255));
        panelSeleccion.add(lblPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, 23));

        lblPlayer2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPlayer2.setForeground(new java.awt.Color(255, 255, 255));
        panelSeleccion.add(lblPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 120, 23));

        lblPlayer3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPlayer3.setForeground(new java.awt.Color(255, 255, 255));
        panelSeleccion.add(lblPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 120, 30));

        lblMensajeCombo.setFont(new java.awt.Font("Arial", 3, 13)); // NOI18N
        lblMensajeCombo.setForeground(new java.awt.Color(255, 0, 0));
        panelSeleccion.add(lblMensajeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 360, 30));

        jPanel1.add(panelSeleccion);
        panelSeleccion.setBounds(160, 10, 730, 220);

        PanelJuego.setOpaque(false);
        PanelJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POZO:");
        PanelJuego.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        lblPozo.setBackground(new java.awt.Color(255, 0, 51));
        lblPozo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPozo.setOpaque(true);
        PanelJuego.add(lblPozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 39, 26));

        lblNum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNum.setForeground(new java.awt.Color(255, 255, 255));
        PanelJuego.add(lblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 103, 40, 36));

        lblBolilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/amarilla.png"))); // NOI18N
        PanelJuego.add(lblBolilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 294, 285));

        btnSortear.setText("Sortear");
        PanelJuego.add(btnSortear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/1.png"))); // NOI18N
        PanelJuego.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/74.png"))); // NOI18N
        PanelJuego.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/19.png"))); // NOI18N
        PanelJuego.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/100.png"))); // NOI18N
        PanelJuego.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/27.png"))); // NOI18N
        PanelJuego.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 120, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/20.png"))); // NOI18N
        PanelJuego.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/28.png"))); // NOI18N
        PanelJuego.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 480, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/59.png"))); // NOI18N
        PanelJuego.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/33.png"))); // NOI18N
        PanelJuego.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/50.png"))); // NOI18N
        PanelJuego.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/6.png"))); // NOI18N
        PanelJuego.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Miniaturas/43.png"))); // NOI18N
        PanelJuego.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, -1, -1));

        jPanel1.add(PanelJuego);
        PanelJuego.setBounds(0, 10, 1070, 640);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondomesa.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1070, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // <editor-fold defaultstate="collapsed" desc=" Boton de Play ">
    public void CargarVentanasJugadores(){
        
        
        ClaseObservador Observador = Patrones.Observer.ClaseObservador.getInstancia();
        dEmpresa Empresa = Dominio.dEmpresa.getInstancia();
        vBingoGame ventanaJuego = new vBingoGame(Empresa, Observador);

        //Ventana Player 1
        vPlayer1 ventanaPlayer1 = new vPlayer1(Observador);
        vPlayer2 ventanaPlayer2 = new vPlayer2(Observador);
        vPlayer3 ventanaPlayer3 = null;
        //los agrego al observador
        Observador.addObserver(ventanaPlayer1);
        Observador.addObserver(ventanaPlayer2);

        //centra la ventana
        ventanaJuego.setLocationRelativeTo(null);
        ventanaPlayer1.setLocationRelativeTo(null);
        ventanaPlayer2.setLocationRelativeTo(null);

        ///
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        /**************/
        Point middle = new Point(screenSize.width / 2, screenSize.height / 2);
        /****************/
        Point newLocation = new Point(middle.x - (ventanaJuego.getWidth() / 2), 
                                      middle.y - (ventanaJuego.getHeight() / 2));
        ventanaPlayer1.setLocation(newLocation);
        ventanaPlayer1.setSize(415, 655);
        ///
        ///
        Point newLocation2 = new Point(middle.x, 
                                      middle.y - (ventanaJuego.getHeight() / 2));
        ventanaPlayer2.setLocation(newLocation2);
        ventanaPlayer2.setSize(415, 655);
        ///
        //mostramos la ventana
        ventanaPlayer1.setTitle(this.lblPlayer1.getText());
        ventanaPlayer2.setTitle(this.lblPlayer2.getText());
        
        if(this.comboSelect.getSelectedIndex() == 1){
            ventanaPlayer3 = new vPlayer3(Observador);
            Observador.addObserver(ventanaPlayer3);
            ventanaPlayer3.setLocationRelativeTo(null);
            ///
            
            Point newLocation3 = new Point(middle.x - (ventanaJuego.getWidth() / 2 + 100), 
                                          middle.y - (ventanaJuego.getHeight() / 2));
            ventanaPlayer3.setLocation(newLocation3);
            ventanaPlayer3.setSize(415, 655);
            ventanaPlayer3.setTitle(this.lblPlayer3.getText());
        ///
        }

        ventanaPlayer1.setVisible(true);
        ventanaPlayer2.setVisible(true);
        if(ventanaPlayer3 != null)
            ventanaPlayer3.setVisible(true);
        this.panelSeleccion.setVisible(false);
        this.PanelJuego.setVisible(true);
    }     // </editor-fold>
    public boolean checkAllOnline(String cantidad){
        boolean bandera = false;
        switch(cantidad){
            case "2":
                if(this.lblEstado1.getText().equalsIgnoreCase("ONLINE") && this.lblEstado2.getText().equalsIgnoreCase("ONLINE")){
                    bandera = true;
                }
                break;
            case "3":
                if(this.lblEstado1.getText().equalsIgnoreCase("ONLINE") && this.lblEstado2.getText().equalsIgnoreCase("ONLINE") && this.lblEstado3.getText().equalsIgnoreCase("ONLINE")){
                    bandera = true;
                }
                break;
            default:
                break;
        }
        return bandera;
    }
    // <editor-fold defaultstate="collapsed" desc=" Combo de Seleccion Jugadores ">
    
    private void comboSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSelectItemStateChanged
        // TODO add your handling code here:
        if(this.lblEstado3.getText().equalsIgnoreCase("OFFLINE")){
                if(this.comboSelect.getSelectedIndex() == 0){
                    this.label1010.setVisible(true);//label Player1 Titulo
                    this.label123.setVisible(true);//label Player2 Titulo
                    this.label12313.setVisible(false); //label Player3 Titulo
                    this.lblPlayer1.setVisible(true); //label User name
                    this.lblPlayer2.setVisible(true);//label User name
                    this.lblPlayer3.setVisible(false);//label User name

                    this.lblEstado3.setVisible(false);
                    if(this.lblEstado1.getText().equalsIgnoreCase("OFFLINE")){
                        this.panelLogin1.setVisible(true);
                    }
                    if(this.lblEstado2.getText().equalsIgnoreCase("OFFLINE")){
                        this.panelLogin2.setVisible(true);
                    }
                    this.panelLogin3.setVisible(false);
                }else if(this.comboSelect.getSelectedIndex() == 1){
                    this.label1010.setVisible(true);
                    this.label123.setVisible(true);
                    this.label12313.setVisible(true);
                    this.lblPlayer1.setVisible(true);
                    this.lblPlayer2.setVisible(true);
                    this.lblPlayer3.setVisible(true);
                    if(this.lblEstado1.getText().equalsIgnoreCase("OFFLINE")){
                        this.panelLogin1.setVisible(true);
                    }
                    if(this.lblEstado2.getText().equalsIgnoreCase("OFFLINE")){
                        this.panelLogin2.setVisible(true);
                    }
                    this.lblEstado3.setVisible(true);
                    this.panelLogin3.setVisible(true);
                }
        }else{
            if(this.comboSelect.getSelectedIndex() != 1){
                //JOptionPane.showMessageDialog(this, "El Jugador 3 debe hacer Logout para poder cambiar", "Combo Seleccion", JOptionPane.INFORMATION_MESSAGE);
                this.lblMensajeCombo.setText("El Jugador 3 debe hacer Logout para poder cambiar");
                
                this.comboSelect.setSelectedIndex(1);// 3 Personas
            }
                
                
            //Maxi@gmail.com
        }
        
    }//GEN-LAST:event_comboSelectItemStateChanged
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc=" Al Abrir Ventana WindowsOpened ">
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.label1010.setVisible(true);
        this.label123.setVisible(true);
        this.label12313.setVisible(false);
        this.lblPlayer1.setVisible(true); //label User name
        this.lblPlayer2.setVisible(true);//label User name
        this.lblPlayer3.setVisible(false);//label User name
        
        this.panelLogin1.setVisible(true);
        this.panelLogin2.setVisible(true);
        this.panelLogin3.setVisible(false);
        
        
        this.PanelJuego.setVisible(false);
        
        this.lblEstado3.setVisible(false);
        
        this.btnLogout1.setVisible(false);
        this.btnLogout2.setVisible(false);
        this.btnLogout3.setVisible(false);
        clicks = 0;
        si = 0;
        no=0;
        elJuego = new cJuego();
    }//GEN-LAST:event_formWindowOpened
    // </editor-fold>
    private void comboColoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboColoresItemStateChanged
        // TODO add your handling code here:
        this.observer.setChang(this.comboColores.getSelectedItem().toString());
    }//GEN-LAST:event_comboColoresItemStateChanged
    
    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        try {
            // TODO add your handling code here:
            LoginUser(evt);
        } catch (Exception ex) {
            Logger.getLogger(vBingoGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin2ActionPerformed
        try {
            // TODO add your handling code here:
            LoginUser(evt);
        } catch (Exception ex) {
            Logger.getLogger(vBingoGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogin2ActionPerformed

    private void btnLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin3ActionPerformed
        try {
            // TODO add your handling code here:
            LoginUser(evt);
        } catch (Exception ex) {
            Logger.getLogger(vBingoGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogin3ActionPerformed

    
    
    private void comboSelectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboSelectFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSelectFocusGained

    private void comboSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboSelectMouseClicked
        // TODO add your handling code here:
        if(!this.comboSelect.isEnabled()){
            JOptionPane.showMessageDialog(this, "Deben salir todos los usuarios Antes de Cambiar de Seleccion", "Combo Seleccion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_comboSelectMouseClicked

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
        LogoutUser(evt);
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
        // TODO add your handling code here:
        LogoutUser(evt);
    }//GEN-LAST:event_btnLogout2ActionPerformed

    private void btnLogout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout3ActionPerformed
        // TODO add your handling code here:
        LogoutUser(evt);
    }//GEN-LAST:event_btnLogout3ActionPerformed
    public void LoginUser(ActionEvent evento) throws Exception{
        String cantidad = this.comboSelect.getSelectedItem().toString();
        String username, password;
        boolean yaLogeado = false;
        if(this.btnLogin1 == evento.getSource()){
            username = this.txtUserName1.getText();
            password = this.txtPassword1.getText();
            if(!"".equals(username) || !"".equalsIgnoreCase(password)){
                cUsuario jugador1 = new cJugador();
                
                jugador1.setUserName(username);
                jugador1.setPassword(password);
                jugador1 = empresa.buscarUsuario(jugador1);
                if(jugador1.getId() < 1){
                    JOptionPane.showMessageDialog(this, "Login Incorrecto, por Favor Verifique su Usuario y Contraseña", "Login", JOptionPane.INFORMATION_MESSAGE);
                }else
                {
                    for (cUsuario u : elJuego.getJugadores()) {
                    if (u.getEmail().equalsIgnoreCase(jugador1.getEmail())) {
                        yaLogeado = true;
                    }
    }
                    if(!yaLogeado){
                        elJuego.getJugadores().add(jugador1);
                        this.panelLogin1.setVisible(false);
                        this.lblEstado1.setText("ONLINE");
                        this.lblPlayer1.setText(jugador1.getUserName());
                        this.btnLogout1.setVisible(true);
                        
                    }else{
                            JOptionPane.showMessageDialog(this, "Ese Jugador ya esta conectado", "Login", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "Completa todos los Campos...", "Login", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }else if(this.btnLogin2 == evento.getSource()){
            username = this.txtUserName2.getText();
            password = this.txtPassword2.getText();
            if(!"".equals(username) || !"".equalsIgnoreCase(password)){
                cUsuario jugador2 = new cJugador();
                
                jugador2.setUserName(username);
                jugador2.setPassword(password);
                jugador2 = empresa.buscarUsuario(jugador2);
                if(jugador2.getId() < 1){
                    JOptionPane.showMessageDialog(this, "Login Incorrecto, por Favor Verifique su Usuario y Contraseña", "Login", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    
                    for (cUsuario u : elJuego.getJugadores()) {
                    if (u.getEmail().equalsIgnoreCase(jugador2.getEmail())) {
                        yaLogeado = true;
                    }
    }
                    if(!yaLogeado){
                        elJuego.getJugadores().add(jugador2);
                        this.panelLogin2.setVisible(false);
                        this.lblEstado2.setText("ONLINE");
                        this.lblPlayer2.setText(jugador2.getUserName());
                        this.btnLogout2.setVisible(true);
                        
                    }else{
                            JOptionPane.showMessageDialog(this, "Ese Jugador ya esta conectado", "Login", JOptionPane.INFORMATION_MESSAGE);
                    }
                    
                }
            }else{
                JOptionPane.showMessageDialog(this, "Completa todos los Campos...", "Login", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }else{
            username = this.txtUserName3.getText();
            password = this.txtPassword3.getText();
            if(!"".equals(username) || !"".equalsIgnoreCase(password)){
                cUsuario jugador3 = new cJugador();
                
                jugador3.setUserName(username);
                jugador3.setPassword(password);
                jugador3 = empresa.buscarUsuario(jugador3);
                if(jugador3.getId() < 1){
                    JOptionPane.showMessageDialog(this, "Login Incorrecto, por Favor Verifique su Usuario y Contraseña", "Login", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    for (cUsuario u : elJuego.getJugadores()) {
                    if (u.getEmail().equalsIgnoreCase(jugador3.getUserName())) {
                        yaLogeado = true;
                    }
    }
                    if(!yaLogeado){
                        elJuego.getJugadores().add(jugador3);
                        this.panelLogin3.setVisible(false);
                        this.lblEstado3.setText("ONLINE");
                        this.lblPlayer3.setText(jugador3.getUserName());
                        this.btnLogout3.setVisible(true);
                        
                    }else{
                            JOptionPane.showMessageDialog(this, "Ese Jugador ya esta conectado", "Login", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "Completa todos los Campos...", "Login", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
        if(checkAllOnline(cantidad)){
            CargarVentanasJugadores();
        }
    }
    public void LogoutUser(ActionEvent evento){
        
        ArrayList<cUsuario> jugadores = elJuego.getJugadores();
        if(this.btnLogout1 == evento.getSource()){
            for (cUsuario u : jugadores) {
                if (u.getUserName().equalsIgnoreCase(this.lblPlayer1.getText())) {
                    jugadores.remove(u);
                    this.panelLogin1.setVisible(true);
                    this.btnLogout1.setVisible(false);
                    this.lblEstado1.setText("OFFLINE");
                    this.lblPlayer1.setText("");
                    break;
                }
            }
        }else if(this.btnLogout2 == evento.getSource()){
            for (cUsuario u : jugadores) {
                if (u.getUserName().equalsIgnoreCase(this.lblPlayer2.getText())) {
                    jugadores.remove(u);
                    this.panelLogin2.setVisible(true);
                    this.btnLogout2.setVisible(false);
                    this.lblEstado2.setText("OFFLINE");
                    this.lblPlayer2.setText("");
                    break;
                }
            }
        }else{
            for (cUsuario u : jugadores) {
                if (u.getUserName().equalsIgnoreCase(this.lblPlayer3.getText())) {
                    jugadores.remove(u);
                    this.panelLogin3.setVisible(true);
                    this.btnLogout3.setVisible(false);
                    this.lblEstado3.setText("OFFLINE");
                    this.lblPlayer3.setText("");
                    break;
                }
            }
        }
        
    }
    
    public void CargarParametrosJuego(int pCantJugadores) throws cDatosException{
        cConfiguracion config = new cConfiguracion();
        try{
            config = empresa.traerConfiguracion(2);
        }catch(Exception ex){
            throw new cDatosException("ERROR al Traer Configuracion del Juego /vBingoGame: " + ex.getMessage());
        }
        /// Cantidad de fila * Columna y todo esto * Cantidad de Cartones en total
        int CantNumeros = (config.getFilasCarton() * config.getColumnasCarton() ) * (config.getCartonesXJugador()*pCantJugadores);
        Numeros = new Integer[CantNumeros];
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vBingoGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelJuego;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnLogin2;
    private javax.swing.JButton btnLogin3;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnLogout3;
    private javax.swing.JButton btnSortear;
    private javax.swing.JComboBox comboColores;
    private javax.swing.JComboBox comboSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1010;
    private javax.swing.JLabel label123;
    private javax.swing.JLabel label12313;
    private javax.swing.JLabel lblBolilla;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblEstado3;
    private javax.swing.JLabel lblMensajeCombo;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblPlayer3;
    private javax.swing.JLabel lblPozo;
    private javax.swing.JPanel panelLogin1;
    private javax.swing.JPanel panelLogin2;
    private javax.swing.JPanel panelLogin3;
    private javax.swing.JPanel panelSeleccion;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JPasswordField txtPassword3;
    private javax.swing.JTextField txtUserName1;
    private javax.swing.JTextField txtUserName2;
    private javax.swing.JTextField txtUserName3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        
    }
}
