/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import Common.Utilidades;
import Common.cConfiguracion;
import Common.cDatosException;
import Common.cJuego;
import Dominio.dEmpresa;
import Patrones.Observer.ClaseObservador;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maxi
 */
public class vBingoGame extends javax.swing.JFrame implements Observer{
    private dEmpresa empresa;
    private ClaseObservador observer;
    private vPlayer1 Iplayer1;
    private static cJuego JuegoActivo;
    private Integer[] Numeros;
    public static int clicks;
    public static int si;
    public static int no;
    /**
     * Creates new form BingoGame
     */
    public vBingoGame() {
        initComponents();
    }
    public vBingoGame(dEmpresa pEmp, ClaseObservador pObservador) {
        empresa = pEmp;
        observer = pObservador;
        Iplayer1 = new vPlayer1(empresa, observer);
        
        observer.addObserver(Iplayer1);
        initComponents();
    }
    public vBingoGame(ClaseObservador pObservador) {
        observer = pObservador;
        initComponents();
    }
    public vBingoGame(dEmpresa pEmp) {
        empresa = pEmp;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelJuego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPozo = new javax.swing.JLabel();
        btnGirar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSorteo = new javax.swing.JTable();
        lblNum = new javax.swing.JLabel();
        lblEncontro = new javax.swing.JLabel();
        lblNoEncontro = new javax.swing.JLabel();
        comboColores = new javax.swing.JComboBox();
        panelSeleccion = new javax.swing.JPanel();
        label1010 = new javax.swing.JLabel();
        label123 = new javax.swing.JLabel();
        btnPlayGame = new javax.swing.JButton();
        comboSelect = new javax.swing.JComboBox();
        label12313 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelLogin1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnLogin1 = new javax.swing.JButton();
        panelLogin2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        btnLogin2 = new javax.swing.JButton();
        panelLogin3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        btnLogin3 = new javax.swing.JButton();
        lblEstado1 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        lblEstado3 = new javax.swing.JLabel();
        btnLogout1 = new javax.swing.JButton();
        btnLogout2 = new javax.swing.JButton();
        btnLogout3 = new javax.swing.JButton();
        lblPlayer1 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        lblPlayer3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        PanelJuego.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POZO:");

        lblPozo.setBackground(new java.awt.Color(255, 0, 51));
        lblPozo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPozo.setOpaque(true);

        btnGirar.setText("Sortear");
        btnGirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirarActionPerformed(evt);
            }
        });

        tableSorteo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tableSorteo.setToolTipText("");
        jScrollPane1.setViewportView(tableSorteo);

        lblNum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNum.setForeground(new java.awt.Color(255, 255, 255));

        lblEncontro.setForeground(new java.awt.Color(255, 255, 255));
        lblEncontro.setText("jLabel4");

        lblNoEncontro.setForeground(new java.awt.Color(255, 255, 255));
        lblNoEncontro.setText("jLabel4");

        javax.swing.GroupLayout PanelJuegoLayout = new javax.swing.GroupLayout(PanelJuego);
        PanelJuego.setLayout(PanelJuegoLayout);
        PanelJuegoLayout.setHorizontalGroup(
            PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPozo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGirar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblEncontro)
                        .addGap(18, 18, 18)
                        .addComponent(lblNoEncontro)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelJuegoLayout.setVerticalGroup(
            PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJuegoLayout.createSequentialGroup()
                .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblNum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPozo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnGirar)
                                .addComponent(lblEncontro)
                                .addComponent(lblNoEncontro)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.add(PanelJuego);
        PanelJuego.setBounds(270, 320, 510, 300);

        comboColores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rojo", "Negro", "Amarillo" }));
        comboColores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboColoresItemStateChanged(evt);
            }
        });
        jPanel1.add(comboColores);
        comboColores.setBounds(110, 10, 56, 20);

        panelSeleccion.setOpaque(false);
        panelSeleccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1010.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label1010.setForeground(new java.awt.Color(255, 255, 255));
        label1010.setText("Player 1: ");
        panelSeleccion.add(label1010, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        label123.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label123.setForeground(new java.awt.Color(255, 255, 255));
        label123.setText("Player 2:");
        panelSeleccion.add(label123, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        btnPlayGame.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnPlayGame.setText("Play!");
        btnPlayGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayGameActionPerformed(evt);
            }
        });
        panelSeleccion.add(btnPlayGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 189, 26));

        comboSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3" }));
        comboSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSelectItemStateChanged(evt);
            }
        });
        panelSeleccion.add(comboSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 47, -1));

        label12313.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label12313.setForeground(new java.awt.Color(255, 255, 255));
        label12313.setText("Player 3: ");
        panelSeleccion.add(label12313, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de Jugadores");
        panelSeleccion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        panelLogin1.setPreferredSize(new java.awt.Dimension(187, 106));

        jLabel4.setText("Usuario");

        jLabel6.setText("Password");

        btnLogin1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin1.setText("Login");

        javax.swing.GroupLayout panelLogin1Layout = new javax.swing.GroupLayout(panelLogin1);
        panelLogin1.setLayout(panelLogin1Layout);
        panelLogin1Layout.setHorizontalGroup(
            panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogin1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLogin1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelLogin1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLogin1Layout.setVerticalGroup(
            panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnLogin1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelSeleccion.add(panelLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 110));

        jLabel8.setText("Usuario");

        jLabel7.setText("Password");

        btnLogin2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin2.setText("Login");

        javax.swing.GroupLayout panelLogin2Layout = new javax.swing.GroupLayout(panelLogin2);
        panelLogin2.setLayout(panelLogin2Layout);
        panelLogin2Layout.setHorizontalGroup(
            panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogin2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLogin2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
            .addGroup(panelLogin2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLogin2Layout.setVerticalGroup(
            panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLogin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin2)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelSeleccion.add(panelLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        panelLogin3.setPreferredSize(new java.awt.Dimension(187, 106));

        jLabel9.setText("Password");

        jLabel10.setText("Usuario");

        btnLogin3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin3.setText("Login");

        javax.swing.GroupLayout panelLogin3Layout = new javax.swing.GroupLayout(panelLogin3);
        panelLogin3.setLayout(panelLogin3Layout);
        panelLogin3Layout.setHorizontalGroup(
            panelLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogin3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLogin3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogin3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panelLogin3Layout.setVerticalGroup(
            panelLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogin3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLogin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSeleccion.add(panelLogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        lblEstado1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstado1.setForeground(new java.awt.Color(0, 204, 51));
        lblEstado1.setText("OFFLINE");
        panelSeleccion.add(lblEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        lblEstado2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstado2.setForeground(new java.awt.Color(0, 204, 51));
        lblEstado2.setText("OFFLINE");
        panelSeleccion.add(lblEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        lblEstado3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstado3.setForeground(new java.awt.Color(0, 204, 51));
        lblEstado3.setText("OFFLINE");
        panelSeleccion.add(lblEstado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        btnLogout1.setText("Logout");
        panelSeleccion.add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        btnLogout2.setText("Logout");
        panelSeleccion.add(btnLogout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        btnLogout3.setText("Logout");
        panelSeleccion.add(btnLogout3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        lblPlayer1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPlayer1.setForeground(new java.awt.Color(255, 255, 255));
        panelSeleccion.add(lblPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 23));

        lblPlayer2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPlayer2.setForeground(new java.awt.Color(255, 255, 255));
        panelSeleccion.add(lblPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 80, 23));

        lblPlayer3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPlayer3.setForeground(new java.awt.Color(255, 255, 255));
        panelSeleccion.add(lblPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 80, 30));

        jPanel1.add(panelSeleccion);
        panelSeleccion.setBounds(160, 10, 730, 310);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondomesa.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1070, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // <editor-fold defaultstate="collapsed" desc=" Boton de Play ">
       
    private void btnPlayGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayGameActionPerformed
        // TODO add your handling code here:
        ClaseObservador Observador = Patrones.Observer.ClaseObservador.getInstancia();
        dEmpresa Empresa = Dominio.dEmpresa.getInstancia();
        vBingoGame ventanaJuego = new vBingoGame(Empresa, Observador);
        //Ventana Player 1
        vPlayer1 ventanaPlayer1 = new vPlayer1(Observador);
        vPlayer1 ventanaPlayer2 = new vPlayer1(Observador);
        vPlayer1 ventanaPlayer3 = null;
        //los agrego al observador
        Observador.addObserver(ventanaPlayer1);
        Observador.addObserver(ventanaPlayer2);
        
        //centra la ventana
        ventanaJuego.setLocationRelativeTo(null);
        ventanaPlayer1.setLocationRelativeTo(null);
        ventanaPlayer2.setLocationRelativeTo(null);
        
        ///
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Point middle = new Point(screenSize.width / 2, screenSize.height / 2);
        Point newLocation = new Point(middle.x - (ventanaJuego.getWidth() / 2), 
                                      middle.y - (ventanaJuego.getHeight() / 2));
        ventanaPlayer1.setLocation(newLocation);
        ventanaPlayer1.setSize(415, 655);
        ///
        ///
        Dimension screenSize2 = Toolkit.getDefaultToolkit().getScreenSize();
        Point middle2 = new Point(screenSize2.width / 2, screenSize2.height / 2);
        Point newLocation2 = new Point(middle2.x, 
                                      middle2.y - (ventanaJuego.getHeight() / 2));
        ventanaPlayer2.setLocation(newLocation2);
        ventanaPlayer2.setSize(415, 655);
        ///
        //mostramos la ventana
        ventanaPlayer1.setTitle("Jugador Numero 1");
        ventanaPlayer2.setTitle("Jugador Numero 2");
        if(this.comboSelect.getSelectedIndex() == 1){
            ventanaPlayer3 = new vPlayer1(Observador);
            Observador.addObserver(ventanaPlayer3);
            ventanaPlayer3.setLocationRelativeTo(null);
            ///
        Dimension screenSize3 = Toolkit.getDefaultToolkit().getScreenSize();
        Point middle3 = new Point(screenSize3.width / 2, screenSize3.height / 2);
        Point newLocation3 = new Point(middle3.x - (ventanaJuego.getWidth() / 2 + 100), 
                                      middle3.y - (ventanaJuego.getHeight() / 2));
        ventanaPlayer3.setLocation(newLocation3);
        ventanaPlayer3.setSize(415, 655);
        ventanaPlayer3.setTitle("Jugador Numero 3");
        ///
        }
        
        ventanaPlayer1.setVisible(true);
        ventanaPlayer2.setVisible(true);
        if(ventanaPlayer3 != null)
            ventanaPlayer3.setVisible(true);
        cargarNumerosTablero();
        this.panelSeleccion.setVisible(false);
        this.PanelJuego.setVisible(true);
    }//GEN-LAST:event_btnPlayGameActionPerformed
     // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc=" Combo de Seleccion Jugadores ">
    
    private void comboSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSelectItemStateChanged
        // TODO add your handling code here:
        if(this.comboSelect.getSelectedIndex() == 0){
            this.label1010.setVisible(true);//label Player1 Titulo
            this.label123.setVisible(true);//label Player2 Titulo
            this.label12313.setVisible(false); //label Player3 Titulo
            this.lblPlayer1.setVisible(true); //label User name
            this.lblPlayer2.setVisible(true);//label User name
            this.lblPlayer3.setVisible(false);//label User name
            
            this.lblEstado3.setVisible(false);
            
            this.panelLogin1.setVisible(true);
            this.panelLogin2.setVisible(true);
            this.panelLogin3.setVisible(false);
        }else if(this.comboSelect.getSelectedIndex() == 1){
            this.label1010.setVisible(true);
            this.label123.setVisible(true);
            this.label12313.setVisible(true);
            this.lblPlayer1.setVisible(true);
            this.lblPlayer2.setVisible(true);
            this.lblPlayer3.setVisible(true);
            
            this.lblEstado3.setVisible(true);
            
            this.panelLogin1.setVisible(true);
            this.panelLogin2.setVisible(true);
            this.panelLogin3.setVisible(true);
        }
    }//GEN-LAST:event_comboSelectItemStateChanged
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc=" Al Abrir Ventana WindowsOpened ">
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.label1010.setVisible(true);
        this.label123.setVisible(true);
        this.label12313.setVisible(false);
        this.lblPlayer1.setVisible(true); //label User name
        this.lblPlayer2.setVisible(true);//label User name
        this.lblPlayer3.setVisible(false);//label User name
        
        this.panelLogin1.setVisible(true);
        this.panelLogin2.setVisible(true);
        this.panelLogin3.setVisible(false);
        
        this.btnPlayGame.setVisible(true);
        this.tableSorteo.getTableHeader().setVisible(false);
        this.PanelJuego.setVisible(false);
        
        this.lblEstado3.setVisible(false);
        
        this.btnLogout1.setVisible(false);
        this.btnLogout2.setVisible(false);
        this.btnLogout3.setVisible(false);
        clicks = 0;
        si = 0;
        no=0;
    }//GEN-LAST:event_formWindowOpened
    // </editor-fold>
    private void comboColoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboColoresItemStateChanged
        // TODO add your handling code here:
        this.observer.setChang(this.comboColores.getSelectedItem().toString());
    }//GEN-LAST:event_comboColoresItemStateChanged
    
    private void btnGirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirarActionPerformed
        // TODO add your handling code here:
        int numeroAleatorio = (int) (Math.random()*Numeros.length+1);
        this.lblNum.setText(String.valueOf(clicks++));
        ElegirNumero();
    }//GEN-LAST:event_btnGirarActionPerformed
    private void cargarNumerosTablero(){
        if(this.Numeros == null){
            this.Numeros = new Integer[100]; 
            DefaultTableModel tm = (DefaultTableModel) this.tableSorteo.getModel();
            //Vacio las Rows
            tm.setRowCount(0);
            for(int i = 1; i < 92; i+=10){
                tm.addRow(new Object[]{new Integer(i), new Integer(i+1), new Integer(i+2), new Integer(i+3), new Integer(i+4), new Integer(i+5)
                , new Integer(i+6), new Integer(i+7), new Integer(i+8), new Integer(i+9)});
                tableSorteo.setModel(tm);
            }
        }
    }
    public void ElegirNumero(){
        int numeroAleatorio = (int) (Math.random()*Numeros.length+1);
        boolean encontro = false;
        DefaultTableModel tm = (DefaultTableModel) this.tableSorteo.getModel();
        
            for (int i = tm.getRowCount() - 1; i >= 0; --i) {
                for (int j = tm.getColumnCount() - 1; j >= 0; --j) {
                    if (tm.getValueAt(i, j).equals(numeroAleatorio)) {
                        // what if value is not unique?
                        int numero = (int)tm.getValueAt(i, j);
                        tm.setValueAt("@", i, j);//"'"+numeroAleatorio +"'"
                        encontro = true;
                        this.lblEncontro.setText(String.valueOf(si++));
                        break;
                    }
                }
            }
        if(!encontro){
            ElegirNumero();
            this.lblNoEncontro.setText(String.valueOf(no++));
        }
        
        
    }
    public void CargarParametrosJuego(int pCantJugadores) throws cDatosException{
        cConfiguracion config = new cConfiguracion();
        try{
            config = empresa.traerConfiguracion(2);
        }catch(Exception ex){
            throw new cDatosException("ERROR al Traer Configuracion del Juego /vBingoGame: " + ex.getMessage());
        }
        /// Cantidad de fila * Columna y todo esto * Cantidad de Cartones en total
        int CantNumeros = (config.getFilasCarton() * config.getColumnasCarton() ) * (config.getCartonesXJugador()*pCantJugadores);
        Numeros = new Integer[CantNumeros];
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vBingoGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelJuego;
    private javax.swing.JButton btnGirar;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnLogin2;
    private javax.swing.JButton btnLogin3;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnLogout3;
    private javax.swing.JButton btnPlayGame;
    private javax.swing.JComboBox comboColores;
    private javax.swing.JComboBox comboSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel label1010;
    private javax.swing.JLabel label123;
    private javax.swing.JLabel label12313;
    private javax.swing.JLabel lblEncontro;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblEstado3;
    private javax.swing.JLabel lblNoEncontro;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblPlayer3;
    private javax.swing.JLabel lblPozo;
    private javax.swing.JPanel panelLogin1;
    private javax.swing.JPanel panelLogin2;
    private javax.swing.JPanel panelLogin3;
    private javax.swing.JPanel panelSeleccion;
    private javax.swing.JTable tableSorteo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        
    }
}
