/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import Common.Utilidades;
import Common.cDatosException;
import Common.cJuego;
import Dominio.dEmpresa;
import Patrones.Observer.ClaseObservador;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maxi
 */
public class vBingoGame extends javax.swing.JFrame implements Observer{
    private dEmpresa empresa;
    private ClaseObservador observer;
    private vPlayer1 Iplayer1;
    private static cJuego JuegoActivo;
    private Integer[] Numeros;
    public static int clicks;
    public static int si;
    public static int no;
    /**
     * Creates new form BingoGame
     */
    public vBingoGame() {
        initComponents();
    }
    public vBingoGame(dEmpresa pEmp, ClaseObservador pObservador) {
        empresa = pEmp;
        observer = pObservador;
        Iplayer1 = new vPlayer1(empresa, observer);
        
        observer.addObserver(Iplayer1);
        initComponents();
    }
    public vBingoGame(ClaseObservador pObservador) {
        observer = pObservador;
        initComponents();
    }
    public vBingoGame(dEmpresa pEmp) {
        empresa = pEmp;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelJuego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPozo = new javax.swing.JLabel();
        btnGirar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSorteo = new javax.swing.JTable();
        lblNum = new javax.swing.JLabel();
        lblEncontro = new javax.swing.JLabel();
        lblNoEncontro = new javax.swing.JLabel();
        comboColores = new javax.swing.JComboBox();
        panelSeleccion = new javax.swing.JPanel();
        lblPlayer1 = new javax.swing.JLabel();
        comboPlayer1 = new javax.swing.JComboBox();
        lblPlayer2 = new javax.swing.JLabel();
        comboPlayer2 = new javax.swing.JComboBox();
        btnPlayGame = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboSelect = new javax.swing.JComboBox();
        comboPlayer3 = new javax.swing.JComboBox();
        lblPlayer3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        PanelJuego.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("POZO:");

        lblPozo.setBackground(new java.awt.Color(255, 0, 51));
        lblPozo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPozo.setOpaque(true);

        btnGirar.setText("Girar");
        btnGirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirarActionPerformed(evt);
            }
        });

        tableSorteo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tableSorteo.setToolTipText("");
        jScrollPane1.setViewportView(tableSorteo);

        lblNum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNum.setForeground(new java.awt.Color(255, 255, 255));

        lblEncontro.setForeground(new java.awt.Color(255, 255, 255));
        lblEncontro.setText("jLabel4");

        lblNoEncontro.setForeground(new java.awt.Color(255, 255, 255));
        lblNoEncontro.setText("jLabel4");

        javax.swing.GroupLayout PanelJuegoLayout = new javax.swing.GroupLayout(PanelJuego);
        PanelJuego.setLayout(PanelJuegoLayout);
        PanelJuegoLayout.setHorizontalGroup(
            PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJuegoLayout.createSequentialGroup()
                .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelJuegoLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPozo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelJuegoLayout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(btnGirar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEncontro)
                                .addGap(18, 18, 18)
                                .addComponent(lblNoEncontro)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelJuegoLayout.setVerticalGroup(
            PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPozo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGirar)
                            .addComponent(lblNum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJuegoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEncontro)
                            .addComponent(lblNoEncontro))
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel1.add(PanelJuego);
        PanelJuego.setBounds(270, 180, 510, 440);

        comboColores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rojo", "Negro", "Amarillo" }));
        comboColores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboColoresItemStateChanged(evt);
            }
        });
        jPanel1.add(comboColores);
        comboColores.setBounds(110, 10, 56, 20);

        panelSeleccion.setOpaque(false);

        lblPlayer1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPlayer1.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayer1.setText("Player 1: ");

        lblPlayer2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPlayer2.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayer2.setText("Player 2:");

        btnPlayGame.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnPlayGame.setText("Play!");
        btnPlayGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayGameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Carga los Jugadores de la Partida");

        comboSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3" }));
        comboSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSelectItemStateChanged(evt);
            }
        });

        lblPlayer3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPlayer3.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayer3.setText("Player 3: ");

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de Jugadores");

        javax.swing.GroupLayout panelSeleccionLayout = new javax.swing.GroupLayout(panelSeleccion);
        panelSeleccion.setLayout(panelSeleccionLayout);
        panelSeleccionLayout.setHorizontalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPlayGame, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addComponent(lblPlayer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lblPlayer2)
                        .addGap(18, 18, 18)
                        .addComponent(comboPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPlayer3)
                        .addGap(18, 18, 18)
                        .addComponent(comboPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(71, 71, 71)
                        .addComponent(comboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 381, Short.MAX_VALUE))))
        );
        panelSeleccionLayout.setVerticalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayer2)
                    .addComponent(comboPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayer1)
                    .addComponent(lblPlayer3)
                    .addComponent(comboPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnPlayGame, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(panelSeleccion);
        panelSeleccion.setBounds(160, 10, 730, 180);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondomesa.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1070, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayGameActionPerformed
        // TODO add your handling code here:
        ClaseObservador Observador = Patrones.Observer.ClaseObservador.getInstancia();
        dEmpresa Empresa = Dominio.dEmpresa.getInstancia();
        vBingoGame ventanaJuego = new vBingoGame(Empresa, Observador);
        //Ventana Player 1
        vPlayer1 ventanaPlayer1 = new vPlayer1(Observador);
        vPlayer1 ventanaPlayer2 = new vPlayer1(Observador);
        vPlayer1 ventanaPlayer3 = null;
        //los agrego al observador
        Observador.addObserver(ventanaPlayer1);
        Observador.addObserver(ventanaPlayer2);
        
        //centra la ventana
        ventanaJuego.setLocationRelativeTo(null);
        ventanaPlayer1.setLocationRelativeTo(null);
        ventanaPlayer2.setLocationRelativeTo(null);
        
        ///
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Point middle = new Point(screenSize.width / 2, screenSize.height / 2);
        Point newLocation = new Point(middle.x - (ventanaJuego.getWidth() / 2), 
                                      middle.y - (ventanaJuego.getHeight() / 2));
        ventanaPlayer1.setLocation(newLocation);
        ventanaPlayer1.setSize(415, 655);
        ///
        ///
        Dimension screenSize2 = Toolkit.getDefaultToolkit().getScreenSize();
        Point middle2 = new Point(screenSize2.width / 2, screenSize2.height / 2);
        Point newLocation2 = new Point(middle2.x, 
                                      middle2.y - (ventanaJuego.getHeight() / 2));
        ventanaPlayer2.setLocation(newLocation2);
        ventanaPlayer2.setSize(415, 655);
        ///
        //mostramos la ventana
        ventanaPlayer1.setTitle("Jugador Numero 1");
        ventanaPlayer2.setTitle("Jugador Numero 2");
        if(this.comboSelect.getSelectedIndex() == 1){
            ventanaPlayer3 = new vPlayer1(Observador);
            Observador.addObserver(ventanaPlayer1);
            ventanaPlayer3.setLocationRelativeTo(null);
            ///
        Dimension screenSize3 = Toolkit.getDefaultToolkit().getScreenSize();
        Point middle3 = new Point(screenSize3.width / 2, screenSize3.height / 2);
        Point newLocation3 = new Point(middle3.x - (ventanaJuego.getWidth() / 2 + 100), 
                                      middle3.y - (ventanaJuego.getHeight() / 2));
        ventanaPlayer3.setLocation(newLocation3);
        ventanaPlayer3.setSize(415, 655);
        ventanaPlayer3.setTitle("Jugador Numero 3");
        ///
        }
        ventanaPlayer1.setVisible(true);
        ventanaPlayer2.setVisible(true);
        if(ventanaPlayer3 != null)
            ventanaPlayer3.setVisible(true);
        cargarNumerosTablero();
        this.panelSeleccion.setVisible(false);
        this.PanelJuego.setVisible(true);
    }//GEN-LAST:event_btnPlayGameActionPerformed
    private void cargarNumerosTablero(){
        if(this.Numeros == null){
            this.Numeros = new Integer[100]; 
            DefaultTableModel tm = (DefaultTableModel) this.tableSorteo.getModel();
            //Vacio las Rows
            tm.setRowCount(0);
            for(int i = 1; i < 92; i+=10){
                tm.addRow(new Object[]{new Integer(i), new Integer(i+1), new Integer(i+2), new Integer(i+3), new Integer(i+4), new Integer(i+5)
                , new Integer(i+6), new Integer(i+7), new Integer(i+8), new Integer(i+9)});
                tableSorteo.setModel(tm);
            }
        }
    }
    private void comboSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSelectItemStateChanged
        // TODO add your handling code here:
        if(this.comboSelect.getSelectedIndex() == 0){
            this.lblPlayer1.setVisible(true);
            this.lblPlayer2.setVisible(true);
            this.lblPlayer3.setVisible(false);
            
            this.comboPlayer1.setVisible(true);
            this.comboPlayer2.setVisible(true);
            this.comboPlayer3.setVisible(false);
        }else if(this.comboSelect.getSelectedIndex() == 1){
            this.lblPlayer1.setVisible(true);
            this.lblPlayer2.setVisible(true);
            this.lblPlayer3.setVisible(true);
            
            this.comboPlayer1.setVisible(true);
            this.comboPlayer2.setVisible(true);
            this.comboPlayer3.setVisible(true);
        }
    }//GEN-LAST:event_comboSelectItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.lblPlayer1.setVisible(true);
        this.lblPlayer2.setVisible(true);
        this.lblPlayer3.setVisible(false);
        
        this.comboPlayer1.setVisible(true);
        this.comboPlayer2.setVisible(true);
        this.comboPlayer3.setVisible(false);
        
        this.btnPlayGame.setVisible(true);
        this.tableSorteo.getTableHeader().setVisible(false);
        this.PanelJuego.setVisible(false);
        clicks = 0;
        si = 0;
        no=0;
    }//GEN-LAST:event_formWindowOpened

    private void comboColoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboColoresItemStateChanged
        // TODO add your handling code here:
        this.observer.setChang(this.comboColores.getSelectedItem().toString());
    }//GEN-LAST:event_comboColoresItemStateChanged

    private void btnGirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirarActionPerformed
        // TODO add your handling code here:
        int numeroAleatorio = (int) (Math.random()*Numeros.length+1);
        this.lblNum.setText(String.valueOf(clicks++));
        ElegirNumero();
    }//GEN-LAST:event_btnGirarActionPerformed
    public void ElegirNumero(){
        int numeroAleatorio = (int) (Math.random()*Numeros.length+1);
        boolean encontro = false;
        DefaultTableModel tm = (DefaultTableModel) this.tableSorteo.getModel();
        
            for (int i = tm.getRowCount() - 1; i >= 0; --i) {
                for (int j = tm.getColumnCount() - 1; j >= 0; --j) {
                    if (tm.getValueAt(i, j).equals(numeroAleatorio)) {
                        // what if value is not unique?
                        int numero = (int)tm.getValueAt(i, j);
                        tm.setValueAt("@", i, j);//"'"+numeroAleatorio +"'"
                        encontro = true;
                        this.lblEncontro.setText(String.valueOf(si++));
                        break;
                    }
                }
            }
        if(!encontro){
            ElegirNumero();
            this.lblNoEncontro.setText(String.valueOf(no++));
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vBingoGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vBingoGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelJuego;
    private javax.swing.JButton btnGirar;
    private javax.swing.JButton btnPlayGame;
    private javax.swing.JComboBox comboColores;
    private javax.swing.JComboBox comboPlayer1;
    private javax.swing.JComboBox comboPlayer2;
    private javax.swing.JComboBox comboPlayer3;
    private javax.swing.JComboBox comboSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEncontro;
    private javax.swing.JLabel lblNoEncontro;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblPlayer3;
    private javax.swing.JLabel lblPozo;
    private javax.swing.JPanel panelSeleccion;
    private javax.swing.JTable tableSorteo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        
    }
}
