/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import Dominio.dEmpresa;
import Patrones.Observer.ClaseObservador;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.omg.PortableServer.POAManagerPackage.State;

/**
 *
 * @author Maxi
 */
public class vPrincipal extends javax.swing.JFrame {
    private dEmpresa empresa;
    public static vBingoGame ventanaBingo;
    public static int cont;
    /**
     * Creates new form vPrincipal
     */
    public vPrincipal() {
        initComponents();
    }
    public vPrincipal(dEmpresa pEmp) {
        empresa = pEmp;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        menuItemRegistro = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuItemAdministracion = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItemSalir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        btnJugar.setBackground(new java.awt.Color(255, 255, 255));
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/boton (1).png"))); // NOI18N
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jPanel1.add(btnJugar);
        btnJugar.setBounds(310, 20, 170, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bingo-1 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        jMenu7.setText("Archivo");
        jMenu7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        menuItemRegistro.setText("Registro de Jugadores");
        menuItemRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistroActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemRegistro);
        jMenu7.add(jSeparator3);

        MenuItemAdministracion.setText("Ingreso Administrativo");
        MenuItemAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAdministracionActionPerformed(evt);
            }
        });
        jMenu7.add(MenuItemAdministracion);
        jMenu7.add(jSeparator2);
        jMenu7.add(jSeparator1);

        MenuItemSalir.setText("Salir");
        MenuItemSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItemSalirMouseClicked(evt);
            }
        });
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        jMenu7.add(MenuItemSalir);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistroActionPerformed
        // TODO add your handling code here:
        vRegistro ventanaRegistro = new vRegistro(empresa);
        //centra la ventana en la pantalla
        ventanaRegistro.setLocationRelativeTo(null);
        ventanaRegistro.setVisible(true);
    }//GEN-LAST:event_menuItemRegistroActionPerformed

    private void MenuItemAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAdministracionActionPerformed
        // TODO add your handling code here:
        vLogin ventanaLogin = new vLogin(Dominio.dEmpresa.getInstancia());
        //centra la ventana
        ventanaLogin.setLocationRelativeTo(null);
        //mostramos la ventana
        ventanaLogin.setVisible(true);
        
    }//GEN-LAST:event_MenuItemAdministracionActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        if(ventanaBingo!= null){
            ventanaBingo = null;
            
        }
        if(cont == 0){
            ClaseObservador Observador = Patrones.Observer.ClaseObservador.getInstancia();
            dEmpresa Empresa = Dominio.dEmpresa.getInstancia();
            try {
            ventanaBingo = new vBingoGame(Empresa, Observador);
            Observador.addObserver(ventanaBingo); ventanaBingo.setLocation(300, 150);

            ventanaBingo.setTitle("Ventana del Juego");
            ventanaBingo.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(vPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            cont++;
        }
        
        
        
        
       
    }//GEN-LAST:event_btnJugarActionPerformed

    private void MenuItemSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItemSalirMouseClicked
        // TODO add your handling code here:   
      
    }//GEN-LAST:event_MenuItemSalirMouseClicked

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cont = 0;
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemAdministracion;
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem menuItemRegistro;
    // End of variables declaration//GEN-END:variables
}
