/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import Common.Enums;
import Common.Utilidades;
import Common.cDatosException;
import Common.cUsuario;
import Dominio.dEmpresa;
import Patrones.FabricaUsuarios;
import Persistencia.pDatosException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Maxi
 */
public class vRegistro extends javax.swing.JFrame {
    private dEmpresa laEmpresa;
    /**
     * Creates new form vMiRegistro
     */
    public vRegistro() {
        initComponents();
    }
    public vRegistro(dEmpresa pEmp) {
        initComponents();
        laEmpresa = pEmp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        txtPassword1 = new javax.swing.JPasswordField();
        txtId = new javax.swing.JTextField();
        lblTitleId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCant2 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        FechaNacido = new com.toedter.calendar.JDateChooser();
        lblTitleSaldo = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        comboFichas = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        panelTable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAltaCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro de Jugadores"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 170, -1));
        jPanel6.add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 180, -1));

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel6.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 32, -1));

        lblTitleId.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblTitleId.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleId.setText("Id: ");
        jPanel6.add(lblTitleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 36, 49, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 95, 70, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel6.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 115, 175, -1));

        btnAgregar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAgregar.setText("Registrarme");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel6.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 153, 90, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Repeat Pass:");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 153, 120, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha Nacimiento:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 204, -1, -1));
        jPanel6.add(lblCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnReset.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel6.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel6.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 204, 50, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel6.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 224, 175, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido:");
        jLabel7.setMaximumSize(new java.awt.Dimension(50, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(50, 14));
        jLabel7.setName(""); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 95, 70, -1));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel6.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 115, 180, -1));
        jPanel6.add(FechaNacido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 224, -1, -1));

        lblTitleSaldo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblTitleSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleSaldo.setText("SALDO:");
        jPanel6.add(lblTitleSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 20, 60, -1));

        lblSaldo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldo.setText("0");
        jPanel6.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));
        jPanel2.setForeground(new java.awt.Color(204, 102, 0));
        jPanel2.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Comprar Fichas: ");

        comboFichas.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        comboFichas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "100", "150", "200", "250" }));
        comboFichas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFichasItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Valor: ");

        lblValor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblValor.setForeground(new java.awt.Color(255, 255, 255));
        lblValor.setText("200");
        lblValor.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(comboFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(11, 11, 11)
                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(comboFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lblValor))
                .addGap(4, 4, 4))
        );

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 262, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuario:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 36, 80, -1));
        jPanel6.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 61, 175, -1));

        tableAltaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Born"
            }
        ));
        tableAltaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAltaClienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableAltaCliente);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel6.add(panelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 440, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 440));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(this.btnAgregar.getText().equals("Registrarme")) {
            try {
                AgregarNuevoUsuario();
            } catch (Exception ex) {
                Logger.getLogger(vRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                EliminarUsuario();
            } catch (Exception ex) {
                Logger.getLogger(vRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tableAltaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAltaClienteMouseClicked
        // TODO add your handling code here:
        int fila = this.tableAltaCliente.getSelectedRow();

        if (fila >= 0) {
            DefaultTableModel tm = (DefaultTableModel) this.tableAltaCliente.getModel();
            int numFilas = tm.getRowCount();
            if ((fila < numFilas) && (fila >= 0)) {

                // tomo los datos de los tipos existentes
                String id = String.valueOf(tm.getValueAt(fila, 0));
                String Nombre = (String) tm.getValueAt(fila, 1);
                FabricaUsuarios fu = new FabricaUsuarios();
                cUsuario user = fu.getFactoryInstance(String.valueOf(Enums.Gerarquia.JUGADOR));
                int Id = Integer.parseInt(id);
                user.setId(Id);
                try {
                    user = (cUsuario) laEmpresa.buscarUsuario(user);
                } catch (cDatosException ex) {
                    Logger.getLogger(vRegistro.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(vRegistro.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(vRegistro.class.getName()).log(Level.SEVERE, null, ex);
                }
                CargarUsuario(user);
            }
        }
        ChangeBoton(true);
    }//GEN-LAST:event_tableAltaClienteMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
        //this.ChangeBoton(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            this.cargarUsuarios();

        } catch (ParseException ex) {
            Logger.getLogger(vRegistro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(vRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        visualizarModoPerfil(false);
        this.panelTable.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void comboFichasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFichasItemStateChanged
        // TODO add your handling code here:
        String value = this.comboFichas.getSelectedItem().toString();
        int valor = CalcularValorFichas(Integer.parseInt(value));
        this.lblValor.setText(String.valueOf(valor));
    }//GEN-LAST:event_comboFichasItemStateChanged
    public int CalcularValorFichas(int cantidad){
        int unidad = 2;
        return cantidad * 2;
    }
    private void ChangeBoton(boolean bool)
    {
        if(bool == false){
            this.btnAgregar.setText("Agregar");
            this.btnModificar.setVisible(bool);
        }else{
            this.btnAgregar.setText("Eliminar");
            this.btnModificar.setVisible(bool);
        }
        
    }
    private void visualizarModoPerfil(boolean bool){
        this.lblTitleSaldo.setVisible(bool);
        this.lblSaldo.setVisible(bool);
        this.btnModificar.setVisible(bool);
        this.txtId.setVisible(bool);
        this.lblTitleId.setVisible(bool);
    }
    private void AgregarNuevoUsuario() throws Exception{
        cUsuario user = null;
         //**************************/
        FabricaUsuarios fu = new FabricaUsuarios();
         //**************************/
        int num;
        try{
            //Verifica el Ingreso de los Datos Requeridos
            if(Utilidades.passLengthTrust(this.txtPassword.getText(), this.txtPassword1.getText())){
                if(Utilidades.pass1pass2Trust(this.txtPassword.getText(), this.txtPassword1.getText())){
                    if(Utilidades.camposCompletos(this.txtNombre.getText(), this.txtApellido.getText(), this.txtEmail.getText(), this.txtPassword.getText(), this.txtPassword1.getText(), this.txtUserName.getText())){
                        if(Utilidades.validarFecha(Utilidades.FormatearFechaToString(this.FechaNacido.getDate()))){
                            if(Utilidades.validateEmail(this.txtEmail.getText())){
                                String ID = this.txtId.getText();
                                Date Fecha = this.FechaNacido.getDate();
                                //**************************/

                                user = fu.getFactoryInstance(String.valueOf(Enums.Gerarquia.JUGADOR));
                                 //**************************/
                                user.setId(0);
                                user.setNombre(this.txtNombre.getText());
                                user.setApellido(this.txtApellido.getText());
                                user.setEmail(this.txtEmail.getText());
                                user.setPassword(this.txtPassword.getText());
                                user.setUserName(this.txtUserName.getText());
                                user.setFechanacido(Fecha);
                                if(user.QueSoy().equalsIgnoreCase("JUGADOR")){
                                    user.SetearFichas(Integer.parseInt(String.valueOf(this.comboFichas.getSelectedItem())));
                                }
                                boolean Agregado = laEmpresa.agregarUsuario(user);
                                if(Agregado){
                                    this.cargarUsuarios();
                                    this.LimpiarCampos();
                                    //this.miObservador.setChang("Se Agrego Nuevo Cliente.");
                                    JOptionPane.showMessageDialog(this, "Se dado de alta correctamente", "Registro", JOptionPane.INFORMATION_MESSAGE);
                                }else{
                                    JOptionPane.showMessageDialog(this, "Ocurrio un Error al Agregar Usuario nuevo", "Registro", JOptionPane.INFORMATION_MESSAGE);
                                }
                            }else{
                                JOptionPane.showMessageDialog(this, "La Sintaxis Usada en el Email no es correcta", "Registro", JOptionPane.INFORMATION_MESSAGE);
                            }
                        
                        
                    }

                    }else{
                        JOptionPane.showMessageDialog(this, "Debes Completar todos los Campos /n antes de proseguir.", "Registro", JOptionPane.INFORMATION_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Las Contraseñas no Coinciden. \n Por Favor Verifica", "Registro", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "El Largo de tu contraeña " + "/n debe ser de 6 o mas.", "Registro", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception ex){
            Logger.getLogger(pDatosException.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void EliminarUsuario() throws Exception{
        cUsuario unUsuario;
        int num;
        try{
            //Verifica el Ingreso de los Datos Requeridos
            if(this.txtId.getText().length()>0 && this.txtNombre.getText().length() > 0 ){
                    String ID = this.txtId.getText();
                    unUsuario = new cUsuario();
                    num = Integer.parseInt(this.txtId.getText());
                    unUsuario = new cUsuario();
                    unUsuario.setId(num);
                    laEmpresa.eliminarUsuario(unUsuario);
                    this.cargarUsuarios();
                    this.LimpiarCampos();
                    ChangeBoton(false);
                    JOptionPane.showMessageDialog(this, "Se ha Eliminado Correctamente!", "Tipo", JOptionPane.INFORMATION_MESSAGE);
                }

        }catch(Common.cDatosException e){
            JOptionPane.showMessageDialog(this, e.toString(), "Tipo", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            Logger.getLogger(vRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void cargarUsuarios() throws cDatosException, ParseException, Exception{
        ArrayList <cUsuario> losUsuarios = new ArrayList();
        losUsuarios = laEmpresa.buscarTodosUsuarios();
        try {
            //Iterator<cProducto> it = losProductos.iterator();
            //Capturo el Modelo
            DefaultTableModel tm = (DefaultTableModel) tableAltaCliente.getModel();
            //Vacio las Rows
            tm.setRowCount(0);
            //Recorro la Lista
            for(cUsuario user:losUsuarios){
                //Agrego una Nueva Row
                tm.addRow(new Object[]{new Integer(user.getId()), new String(user.getNombre()), new String(Utilidades.FormatearFechaToString(user.getFechanacido()))});
                tableAltaCliente.setModel(tm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Tipo", JOptionPane.ERROR_MESSAGE);
        }
        this.tableAltaCliente.setVisible(false);
    }
    public void CargarUsuario(cUsuario pUser){
        this.txtId.setText(String.valueOf(pUser.getId()));
        this.txtNombre.setText(pUser.getNombre());
        this.txtApellido.setText(pUser.getApellido());
        this.txtPassword.setText(pUser.getPassword());
        this.txtEmail.setText(pUser.getEmail());
        this.FechaNacido.setDate(pUser.getFechanacido());
    }
    private void LimpiarCampos(){
        this.txtId.setText("");
        this.txtUserName.setText("");
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtPassword.setText("");
        this.txtPassword1.setText("");
        this.txtEmail.setText("");
        this.FechaNacido.cleanup();
        this.txtNombre.setFocusable(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaNacido;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox comboFichas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCant2;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTitleId;
    private javax.swing.JLabel lblTitleSaldo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel panelTable;
    javax.swing.JTable tableAltaCliente;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
