/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * vPrincipal.java
 *
 * Created on 22-ene-2010, 14:28:49
 */
package Interfase;

import Common.Utilidades;
import Dominio.dEmpresa;
import Common.cDatosException;
import Common.cTipo;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author administrator
 */
public class vTipo extends javax.swing.JFrame {

    private ArrayList<cTipo> ListaTipos = new ArrayList<cTipo>();

// <editor-fold defaultstate="collapsed" desc=" Generado ">
    /**
     * Creates new form vPrincipal
     */
    public vTipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTiposEli = new javax.swing.JTable();
        txtEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdEliminar = new javax.swing.JTextField();
        txtDescEliminar = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarPorDescripcion = new javax.swing.JTextField();

        setTitle("ABM Tipo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel3.setText("Id:");
        jLabel3.setName("jLabel3"); // NOI18N

        txtId.setName("txtId"); // NOI18N

        jLabel1.setText("Descripción:");
        jLabel1.setName("jLabel1"); // NOI18N

        txtDesc.setName("txtDesc"); // NOI18N

        btnAgregar.setText("Agregar");
        btnAgregar.setName("btnAgregar"); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addComponent(txtId)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblTiposEli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Descripción"
            }
        ));
        tblTiposEli.setName("tblTiposEli"); // NOI18N
        tblTiposEli.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTiposEli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTiposEliMouseClicked(evt);
            }
        });
        tblTiposEli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblTiposEliFocusGained(evt);
            }
        });
        tblTiposEli.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tblTiposEliHierarchyChanged(evt);
            }
        });
        tblTiposEli.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tblTiposEliCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tblTiposEli.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblTiposEliPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblTiposEli);

        txtEliminar.setText("Eliminar");
        txtEliminar.setName("txtEliminar"); // NOI18N
        txtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Id:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setText("Descripción:");
        jLabel4.setName("jLabel4"); // NOI18N

        txtIdEliminar.setName("txtIdEliminar"); // NOI18N
        txtIdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEliminarActionPerformed(evt);
            }
        });

        txtDescEliminar.setName("txtDescEliminar"); // NOI18N

        btnModificar.setText("Modificar");
        btnModificar.setName("btnModificar"); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel6.setText("Buscar por Descripción:");
        jLabel6.setName("jLabel6"); // NOI18N

        txtBuscarPorDescripcion.setName("txtBuscarPorDescripcion"); // NOI18N
        txtBuscarPorDescripcion.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtBuscarPorDescripcionInputMethodTextChanged(evt);
            }
        });
        txtBuscarPorDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarPorDescripcionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPorDescripcionKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEliminar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarPorDescripcion))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescEliminar)
                                    .addComponent(txtIdEliminar))))))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEliminar)
                    .addComponent(btnModificar))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscarPorDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar/Eliminar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ReiniciarControles() {
        this.LimpiarCampos();
        this.CargarIdTipo();
        this.LimpiarList();
        this.CargarDatosList();
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.CargarIdTipo();
        this.txtId.setEnabled(false);
        this.txtIdEliminar.setEnabled(false);
        this.LimpiarList();
        this.CargarDatosList();
        
    }//GEN-LAST:event_formWindowOpened

    private void txtIdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEliminarActionPerformed

    private void txtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarActionPerformed
        cTipo unTipo = new cTipo();
        int num;
        try {
            if (!this.txtIdEliminar.getText().equals("")) {
                num = Integer.parseInt(this.txtIdEliminar.getText());
                unTipo.setId(num);
                empresa.eliminarTipo(unTipo);
                JOptionPane.showMessageDialog(this, "Se dado eliminado correctamente", "Tipo", JOptionPane.INFORMATION_MESSAGE);
                ReiniciarControles();
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un registro", "Tipo", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Common.cDatosException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Tipo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtEliminarActionPerformed

    private void tblTiposEliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblTiposEliPropertyChange


    }//GEN-LAST:event_tblTiposEliPropertyChange

    private void tblTiposEliCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblTiposEliCaretPositionChanged
    }//GEN-LAST:event_tblTiposEliCaretPositionChanged

    private void tblTiposEliHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tblTiposEliHierarchyChanged
    }//GEN-LAST:event_tblTiposEliHierarchyChanged

    private void tblTiposEliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblTiposEliFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTiposEliFocusGained

    private void tblTiposEliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTiposEliMouseClicked
        int fila = this.tblTiposEli.getSelectedRow();

        if (fila >= 0) {
            DefaultTableModel tm = (DefaultTableModel) this.tblTiposEli.getModel();
            int numFilas = tm.getRowCount();
            if ((fila < numFilas) && (fila >= 0)) {

                // tomo los datos de los tipos existentes
                String id = String.valueOf(tm.getValueAt(fila, 0));
                String desc = (String) tm.getValueAt(fila, 1);

                this.txtIdEliminar.setText(id);
                this.txtDescEliminar.setText(desc);

            }
        }
    }//GEN-LAST:event_tblTiposEliMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        cTipo unTipo;
        int num;

        try {
            //Verifica el ingreso de los datos requeridos
            if (this.txtId.getText().length() > 0 && this.txtDesc.getText().length() > 0) {
                String ID = this.txtId.getText().toString();
                //Verifico que hayan ingresado un número
                if (Utilidades.isNumeric(ID) == true) {
                    //Busco si el tipo ya no ha sido ingresado
                    unTipo = new cTipo();
                    num = Integer.parseInt(this.txtId.getText());
                    unTipo.setId(num);
                    unTipo = empresa.buscarTipo(unTipo);
                    ////////////////////////////////////////////////////////////////////////////////////

                    if (unTipo == null) {
                        //Si el tipo no ha sido ingresado lo crea y le pasa los datos para ingresarlo
                        unTipo = new cTipo();
                        unTipo.setId(num);
                        unTipo.setDesc(this.txtDesc.getText());
                        empresa.agregarTipo(unTipo);
                        JOptionPane.showMessageDialog(this, "Se dado de alta correctamente", "Tipo", JOptionPane.INFORMATION_MESSAGE);

                        ReiniciarControles();

                    } else {
                        JOptionPane.showMessageDialog(this, "Id tipo ya existe", "Accion", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El número del código del tipo debe ser un número", "Tipo", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Datos ingresados incorrectamente", "Accion", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Common.cDatosException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Tipo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtBuscarPorDescripcionInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtBuscarPorDescripcionInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPorDescripcionInputMethodTextChanged

    private void txtBuscarPorDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorDescripcionKeyPressed
    }//GEN-LAST:event_txtBuscarPorDescripcionKeyPressed

    private void txtBuscarPorDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorDescripcionKeyReleased
        CargarDatosList(this.txtBuscarPorDescripcion.getText());
    }//GEN-LAST:event_txtBuscarPorDescripcionKeyReleased

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (!this.txtDescEliminar.getText().equals("")
                && !this.txtIdEliminar.getText().equals("")) {

            try {

                Integer num;
                String desc;
                cTipo unTipo = new cTipo();

                num = Integer.parseInt(this.txtIdEliminar.getText());
                desc = this.txtDescEliminar.getText();
                unTipo.setId(num);
                unTipo.setDesc(desc);
                empresa.modificarTipo(unTipo);
                ReiniciarControles();
                JOptionPane.showMessageDialog(this, "Se ha modificado correctamente", "Tipo", JOptionPane.INFORMATION_MESSAGE);

            } catch (cDatosException e) {
                JOptionPane.showMessageDialog(this, e.toString(), "Tipo", JOptionPane.ERROR_MESSAGE);
            }


        } else {
            JOptionPane.showMessageDialog(this, "Datos ingresados incorrectamente", "Accion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vTipo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblTiposEli;
    private javax.swing.JTextField txtBuscarPorDescripcion;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtDescEliminar;
    private javax.swing.JButton txtEliminar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdEliminar;
    // End of variables declaration//GEN-END:variables
// </editor-fold>
    private dEmpresa empresa;

    public vTipo(dEmpresa pEmp) {
        initComponents();
        empresa = pEmp;
    }

    public void CargarIdTipo() {
        int num = 0;
        try {
            num = empresa.generarIdTipo();
            this.txtId.setText(String.valueOf(num));
        } catch (Common.cDatosException e) {
        }
    }

    public void LimpiarList() {
        DefaultTableModel dm = (DefaultTableModel) this.tblTiposEli.getModel();
        dm.setRowCount(0);
        this.tblTiposEli.setModel(dm);//limpia el jtable
    }

    public void CargarDatosList() {
        ArrayList<cTipo> coleccion = new ArrayList<cTipo>();
        try {
            coleccion = empresa.buscarTodosTipos();
            ListaTipos = coleccion;
            Iterator<cTipo> it = coleccion.iterator();
            while (it.hasNext()) {
                cTipo unTipo = it.next();
                DefaultTableModel tm = (DefaultTableModel) tblTiposEli.getModel();
                tm.addRow(new Object[]{new Integer(unTipo.getId()), new String(unTipo.getDesc())});
                tblTiposEli.setModel(tm);
            }
        } catch (Common.cDatosException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Tipo", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void CargarDatosList(String pDesc) {
        try {
            Iterator<cTipo> it = ListaTipos.iterator();
            DefaultTableModel tm = (DefaultTableModel) tblTiposEli.getModel();
            //limiamos el modelo antes de ingresar las nuevas filas
            tm.setRowCount(0);
            while (it.hasNext()) {
                cTipo unTipo = it.next();
                if (unTipo.getDesc().contains(pDesc)) {
                    tm.addRow(new Object[]{new Integer(unTipo.getId()), new String(unTipo.getDesc())});
                }

                tblTiposEli.setModel(tm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Tipo", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void LimpiarCampos() {
        this.txtDesc.setText("");
        this.txtId.setText("");
        this.txtIdEliminar.setText("");
        this.txtDescEliminar.setText("");
        this.txtBuscarPorDescripcion.setText("");
    }
}
